### ISSUE TITLE
Suggestion to submit this project to the OPA ecosystem page

### ISSUE THREAD

**Issue by anderseknert** [carbonetes/brainiac#123]
Hey there! Since there's no better way to reach out on GitHub, I'll do it here. Had a quick look at your policy library, and it looks great. Would love to see your project on the [OPA Ecosystem page](https://www.openpolicyagent.org/docs/latest/ecosystem/), and in the [Awesome OPA](https://github.com/StyraInc/awesome-opa) list. 

Feel free to submit it, and let me know if you need any help doing so. I'm available on the OPA slack as well if you'd like to chat.

**Comment by jaysonsantos05** [comment]
Hi @anderseknert, Thank you for reaching out. We really appreciate you taking the time to review our policy library. We would be thrilled to have our project featured on the OPA Ecosystem page and the Awesome OPA list.
